agents:
  query_decomposer:
    # model: "meta-llama/Llama-3.2-3B-Instruct"
    model: "arcee-ai/Llama-3.1-SuperNova-Lite"
    parameters:
      max_length: 512
      min_length: 50
      temperature: 0.3
      do_sample: true
      top_p: 0.9
      top_k: 50
      num_beams: 4
      max_queries: 3
      min_queries: 1
      repetition_penalty: 1.2
    device:
      dtype: "float16"
      map: "auto"

  chunk_processor:
    model: "recursive"
    parameters:
      size: 500
      overlap: 50
      min_length: 50
      max_chunks: 5
      chunk_type: "sentence"
      separators: ["\n\n", "\n", ".", "!", "?", ",", " "]

  result_reranker:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    parameters:
      top_k: 5
      similarity_threshold: 0.7
      cross_encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      batch_size: 32
      max_length: 512
    device:
      dtype: "float16"
      map: "auto"

  response_generator:
    model: "arcee-ai/Llama-3.1-SuperNova-Lite"
    parameters:
      max_length: 512
      min_length: 50
      num_beams: 4
      temperature: 0.7
      do_sample: true
      top_p: 0.9
      top_k: 50
      repetition_penalty: 1.2
      length_penalty: 1.0
      no_repeat_ngram_size: 3
    device:
      dtype: "float16"
      map: "auto"

source:
  num_sources: 10
  search_type: "google"
  api_version: "v1"
  country: "us"
  language: "en"
  safe_search: true

processing:
  max_chunks: 5
  min_chunk_length: 50
  max_summary_length: 150
  remove_duplicates: true
  clean_text: true
  preserve_order: true