agents:
  ActionDecider:
    model:

  ActionGenerator:
    model: "meta-llama/Llama-3.2-3B-Instruct"
    max_length: 1024
    temperature: 0.9
    num_beams: 4
    do_sample: true
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    max_actions: 2

  ActionExecutor:
    model: "meta-llama/Llama-3.2-3B-Instruct"

  Searcher:
    model: "meta-llama/Llama-3.2-3B-Instruct"
    max_length: 1024
    temperature: 0.9
    num_beams: 4
    do_sample: true
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2
    min_queries: 1
    max_queries: 3

  Summarizer:
    model: "t5-base"
    individual_max_length: 512
    final_max_length: 2048
    temperature: 0.7
    num_beams: 4
    do_sample: true
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2

  Responder:
    model: "arcee-ai/Llama-3.1-SuperNova-Lite"
    max_length: 5120
    temperature: 0.7
    num_beams: 4
    do_sample: True
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.2

num_sources: 3 # Number of sources to search per query

logging_level: "WARNING"
